### ISSUE TITLE
Reverse (PTR) DNS lookups

### ISSUE THREAD

**Issue by plambert** [olegwtf/p5-Net-DNS-Native#4]
Would it be difficult to add support for reverse lookups?

Let me know if there's anything I can do to help.  (I am not a C programmer, so I cannot help with the xs code...)

**Comment by olegwtf** [comment]
May be this is possible, because I found some example which uses getaddrinfo() for this: https://gist.github.com/jirihnidek/bf7a2363e480491da72301b228b35d5d

But I am not interested in this feature for now. So patches or donations are welcome.
